config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :imageposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-light">
  <div class="container">
    <%= link_to "Instravel", root_path, id: "logo", class: "navbar-brand text-dark" %>
    <nav>
      <ul class="nav">
        <%= render 'layouts/search' %>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Profile", current_user, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Settings", edit_user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_search.html.erb
<%# text_fieldにvalue: @serach_params[:name]で初期状態を持たせたい %>
<%= form_with(scope: :search, url: users_path, method: :get, local: true, class: "form-inline") do |f| %>
  <%= f.text_field :name, class: "form-control text-center", placeholder: "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>